### ISSUE TITLE
Error after Installation

### ISSUE THREAD

**Issue by xstable** [josesamuel/logviewer#2]
PhpStorm 2018.2 EAP 
The logs after startup:

`Plugin "Log Viewer" was not loaded: required plugin "org.jetbrains.android" not installed.`

**Comment by josesamuel** [comment]
Is this android studio?

**Comment by josesamuel** [comment]
Fixed, please update to release 3.0

**Comment by shayzalman** [comment]
Im getting this error on PhpStorm, is there a way to overcome this issue on PhpStorm?
Thanks

**Comment by xstable** [comment]
@joomi logcat-plugin dosn't work on phpstorm

**Comment by shayzalman** [comment]
@xstable Thanks for the response
JetBrains shows its compitible with PhpStorm
https://plugins.jetbrains.com/plugin/10015-log-viewer
Will be nice to update it either way
